networks:
  pokemon_network:
    driver: bridge

services:
  db:
    container_name: db-pokemon
    image: mongo
    ports:
      - "27018:27017"
    env_file:
      - ./db/.env
    volumes:
      - ./db:/data/db
    networks:
      - pokemon_network
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - ./mongo-express/.env
    depends_on:
      - db
    networks:
      - pokemon_network


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    networks:
      - pokemon_network
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - pokemon_network
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules